# Site settings
title: Li Mengdi's blog
email: 
description: "Musings of a darkroamer."
baseurl: ""
url: "http://bknieven.github.io"
twitter_username: NULL
github_username: NULL 

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
